# Generated by Django 3.1.2 on 2020-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='sha256',
        ),
        migrations.RemoveField(
            model_name='file',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
