# Generated by Django 3.1.2 on 2020-10-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='date',
            field=models.TextField(),
        ),
    ]
